---
title: "Natural disasters and people displacements in South East Asia"
author: "IHolovko"
date: "17 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape2)
```


```{r cars, warning = FALSE}
idp_dt <- read.table("IDP_data.csv", sep = ";", header = TRUE, stringsAsFactors = FALSE)

# We have three countries for which we don't have data at all or not enough data for the analysis: Brunei, Singapore and Timor-Leste. So we take them out. Also we transform dataset into tibble format for later. 

idp_clean <- idp_dt[-c(7,10,11),]

idp_clean_t <- as.tibble(idp_clean)


# Preparing data for individual countries 

#1. Selecting the countries and variables we need 
country_idp <- idp_clean_t %>%
  filter(Country.Name %in% c("Cambodia", "Indonesia", "Philippines", "Malaysia", "Thailand", "Lao PDR", "Myanmar", "Vietnam")) %>% 
  select(-2)

#2. Transforming variables to numeric format (to be able late to use log() function)

country_idp %>% mutate_at(vars(X2011, X2012, X2013, X2014, X2015, X2016, X2017, X2018, X2019), as.numeric) 
names(country_idp)[2] <- "2011"
names(country_idp)[3]<- "2012"
names(country_idp)[4]<- "2013"
names(country_idp)[5]<- "2014"
names(country_idp)[6]<- "2015"
names(country_idp)[7]<- "2016"
names(country_idp)[8]<- "2017"
names(country_idp)[9]<- "2018"
names(country_idp)[10]<- "2019"

#3. Changing from wide to long format (to be able to use ggplot2)
country_idp_long <- melt(data = country_idp,
                         id.vars = "Country.Name",
                         variable.name = "Year",
                         value.name = "IDPs")
#4. Again transforming to tibble format (as the process of making data long resulted in turning back again the data.frame)

country_idp_long_t <- as.tibble(country_idp_long) %>%
  mutate_at(vars(IDPs), as.numeric) 

#5. Building graphs -> number of IDPs per country per year;

country_idp_bar <- ggplot(country_idp_long_t, aes(x = Year, y = IDPs)) +
  geom_bar(stat = "identity") +
  labs(x = "Year", y = "The number of displacements") +
  facet_wrap(~Country.Name, ncol = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_log10() 

country_idp_bar
  
#Preparing dataset with IDP data for merging with disasters dataset

#1. Renaming columns to unify names 
country_idp_to_merge <- country_idp_long_t %>%
  rename(Country = Country.Name) 


#2. merging both datasets (NOTE: before running the code bellow, please do necessary changes on the dataset on disaster events, see updated "natural disaster script-2.Rmd)

merged_data <- left_join(country_idp_to_merge, country_events, by = c("Year", "Country"))


```


```{echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
